version: "3.9"

services:
  app:
    build: .
    environment:
      PORT: 3012
      DATABASE_ROOT: /database
    volumes:
      - kindra_database:/database
    networks:
      - kindra-net
    expose:
      - "3012"
    restart: unless-stopped

  load-balancer:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
      - "3012:3012"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - kindra-net
    restart: unless-stopped

volumes:
  kindra_database:

networks:
  kindra-net:
    driver: bridge

